version: "3.9"
services:
  openscad:
    build:
      context: .
      args:
        JOBS: 12
        BUILD_TYPE: ${BUILD_TYPE}
        DEBUG: ${DEBUG}
    command: bash -c "gdbserver 0.0.0.0:2000 /openscad/build/openscad --debug=all 2>&1"
    ports:
      - "2000:2000"
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    privileged: true
    container_name: openscad_local_development