version: "3.9"
services:
  openscad:
    build:
      context: .
      args:
        JOBS: 12
        BUILD_TYPE: ${BUILD_TYPE}
        DEBUG: ${DEBUG}
    command: ./startup.sh
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - VSCODE_DRIVEN=${VSCODE_DRIVEN}
    privileged: true
    container_name: openscad_local_development